name: moneyball
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn
      - ipykernel
      - jupyterlab
      - lightgbm
      - prophet